<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="33763" started-at="2018-11-25T11:50:37Z" finished-at="2018-11-25T11:51:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="33763" started-at="2018-11-25T11:50:37Z" finished-at="2018-11-25T11:51:11Z">
      <class name="com.netease.a13.testCase.Login">
        <test-method status="PASS" signature="getloginHome()[pri:0, instance:com.netease.a13.testCase.Login@22555ebf]" name="getloginHome" duration-ms="12657" started-at="2018-11-25T19:50:37Z" finished-at="2018-11-25T19:50:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getloginHome -->
        <test-method status="PASS" signature="testlogin()[pri:0, instance:com.netease.a13.testCase.Login@22555ebf]" name="testlogin" duration-ms="3998" started-at="2018-11-25T19:50:50Z" depends-on-methods="com.netease.a13.testCase.Login.getloginHome" finished-at="2018-11-25T19:50:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testlogin -->
        <test-method status="FAIL" signature="downOrder()[pri:0, instance:com.netease.a13.testCase.Login@22555ebf]" name="downOrder" duration-ms="17082" started-at="2018-11-25T19:50:54Z" depends-on-methods="com.netease.a13.testCase.Login.testlogin" finished-at="2018-11-25T19:51:11Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at com.netease.a13.util.getByLocator.getLocator(getByLocator.java:10)
	at com.netease.a13.testCase.Login.BycourseNow(Login.java:78)
	at com.netease.a13.testCase.Login.downOrder(Login.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- downOrder -->
      </class> <!-- com.netease.a13.testCase.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
